// src/reactapp1.client/src/Shipping/DeliveryOptions.jsx
import styles from "./DeliveryOptions.module.css";

export default function DeliveryOptions({
  options,
  selectionId,
  setSelectionId,
}) {
  return (
    <div>
      {(options ?? []).map((option) => (
        <div key={option.deliveryOptionId} className={styles.option}>
          <div className={styles.selection}>
            <input
              id={option.deliveryOptionId}
              type="radio"
              name="deliveryOption"
              value={option.deliveryOptionId}
              checked={selectionId === option.deliveryOptionId}
              onChange={() => setSelectionId(option.deliveryOptionId)}
            />
            <label htmlFor={option.deliveryOptionId}>{option.name}</label>
          </div>
          <div className={styles.priceAndDescription}>
            <span>
              {option.price.toLocaleString("en-US", {
                style: "currency",
                currency: "USD",
              })}
            </span>
            <span> - </span>
            <span>{option.description}</span>
          </div>
        </div>
      ))}
    </div>
  );
}

// src/website/src/Shipping/DeliveryOptions.svelte
<script>
  let { options = [], selectedId = $bindable(null), onSelect = () => {} } = $props();
  let format = (value) => '$' + Number(value ?? 0).toFixed(2);

  function pick(id) {
    selectedId = id;
    onSelect(id);
  }
</script>

<div class="shipping-options">
  {#each options as option (option.deliveryOptionId)}
    {@const isSelected = selectedId === option.deliveryOptionId}
    <label class="shipping-option" class:selected={isSelected}>
      <input
        type="radio"
        name="deliveryOption"
        value={option.deliveryOptionId}
        checked={isSelected}
        onchange={() => pick(option.deliveryOptionId)}
      />
      <div class="shipping-option-info">
        <div class="shipping-option-name">{option.name}</div>
        <div class="shipping-option-delivery">{option.description}</div>
      </div>
      <div class="shipping-option-price">{format(option.price)}</div>
    </label>
  {/each}
</div>
